export const buttonValues = [
    { name: 'C', id: 'clear' },
    { name: 'DEC', id: 'Decrement'},
    { name: '/', id: 'divide' },
    { name: '7', id: 'seven' },
    { name: '8', id: 'eight' },
    { name: '9', id: 'nine' },
    { name: '*', id: 'multiply' },
    { name: '4', id: 'four' },
    { name: '5', id: 'five' },
    { name: '6', id: 'six' },
    { name: '-', id: 'subtract' },
    { name: '1', id: 'one' },
    { name: '2', id: 'two' },
    { name: '3', id: 'three' },
    { name: '+', id: 'add' },
    { name: '.', id: 'decimal' },
    { name: '0', id: 'zero' },
    { name: '=', id: 'equals' },]